- src/Transport/Config/ContainerConfiguration.cs
- src/Transport/Creation/Clients/AzureServicebusQueueClientCreator.cs
- src/Transport/Receiving/AzureServiceBusDequeueStrategy.cs
PR to address issue #34 when messages are being Dead Lettered due to large number of messages on a queue for a slow handler.
This uses a blocking collection which is sized by the BatchSize configuration setting and the number of handler threads.  
Alan.
> Use BatchSize to limit message consumption to handler performance

- src/NServiceBus.AzureServiceBus.sln.DotSettings
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/When_getting_items_from_circular_buffer.cs
- src/Tests/When_putting_items_into_circular_buffer.cs
- src/Transport/Config/ConfigureAzureServiceBusMessageQueue.cs
- src/Transport/Creation/Clients/CircularBuffer.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/packages.config
Anyone who's using Azure Service Bus transports and using `Bus.Send()` or `Bus.Publish()` in a very tight loop with multiple threads.
Due to a calculation error that can happen with concurrent access an `IndexOutOfRangeException` exception can be thrown
---
Reported in GG: https://groups.google.com/forum/#!topic/particularsoftware/a1GigfXhI94
[`CircularBuffer.Get()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Creation/Clients/CircularBuffer.cs#L166) is not thread safe and may throw exception when used in concurrent mode
Repro:
```c#
Parallel.ForEach(hugeArray, new ParallelOptions() { MaxDegreeOfParallelism = 5 }, item =>
{
Bus.Send(new SomethingCommand
{
Item = item
});
});
```
Connects to #59
> Hotfix-6.3.3 CircularBuffer throws exception

- src/NServiceBus.AzureServiceBus.sln.DotSettings
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/When_getting_items_from_circular_buffer.cs
- src/Tests/When_putting_items_into_circular_buffer.cs
- src/Transport/Config/ConfigureAzureServiceBusMessageQueue.cs
- src/Transport/Creation/Clients/CircularBuffer.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/packages.config
Anyone who's using Azure Service Bus transports and using `Bus.Send()` or `Bus.Publish()` in a very tight loop with multiple threads.
Due to a calculation error that can happen with concurrent access an `IndexOutOfRangeException` exception can be thrown
---
Reported in GG: https://groups.google.com/forum/#!topic/particularsoftware/a1GigfXhI94
[`CircularBuffer.Get()`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/Transport/Creation/Clients/CircularBuffer.cs#L166) is not thread safe and may throw exception when used in concurrent mode
Repro:
```c#
Parallel.ForEach(hugeArray, new ParallelOptions() { MaxDegreeOfParallelism = 5 }, item =>
{
Bus.Send(new SomethingCommand
{
Item = item
});
});
```
Connects to #59
> Hotfix-6.2.2 CircularBuffer throws exception

- src/Tests/Sending/When_comparing_performance_between_built_in_batching_and_manual.cs
- src/Transport/Sending/DefaultOutgoingMessageRouter.cs
- src/Transport/Utils/BrokeredMessageExtensions.cs
Native `BrokeredMessage.Clone` clones ID as well.
> removing CloneWithMessageId extension methods as they are not needed

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
- src/AcceptanceTests/app.config
- src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Receiving/DefaultBrokeredMessagesToIncomingMessagesConverter.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Receiving/UnsupportedBrokeredMessageBodyTypeException.cs
- src/Transport/Sending/DefaultOutgoingMessagesToBrokeredMessagesConverter.cs
- src/Transport/Utils/BrokeredMessageHeaders.cs
Sending poisonous message to DLQ natively.
I put together an acceptance test (`When_receiving_a_message_with_unknown_transport_encoding`) that is a hack. Perhaps would be better to test it in a "unit test". Similar to `When_receiving_incomingmessages_from_queues` so that we can control queue name & connection string.
@yvesgoeleven please review.
> Send poisonous message to DLQ natively

- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/Seam/When_purge_on_startup_is_enabled.cs
- src/Transport/Seam/MessagePump.cs
During the Init phase of MessagePump there is a new check to verify PurgeOnStartup setting value. 
Connect to #100
> PurgeOnStartup should throw because not supported

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/API/APIApprovals.cs
- src/Tests/Configuration/When_configuring_message_senders.cs
- src/Tests/Seam/When_dispatching_messages.cs
- src/Tests/Sending/When_batching_TransportOperations.cs
- src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
- src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs
- src/Tests/Sending/When_routing_outgoingmessages_to_endpoints_with_retries.cs
- src/Transport/Config/DefaultConfigurationValues.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusMessageSenderSettings.cs
- src/Transport/Config/WellKnownConfigurationKeys.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Properties/Resharper.Annotations.g.cs
- src/Transport/Sending/Batcher.cs
- src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs
- src/Transport/Sending/DefaultOutgoingBatchRouter.cs
- src/Transport/Topology/Topologies/ForwardingTopology.cs
- src/Transport/Topology/Topologies/StandardTopology.cs
- src/Transport/Utils/BrokeredMessageExtensions.cs
- src/Transport/Utils/BrokeredMessageHeaders.cs
- src/Transport/Utils/Guard.cs
Replacing ASB native API for `BrokeredMessage.Size` with estimated message size.
Estimated size is based on the following:
- Raw body size in bytes
- Custom headers size (keys and values) in bytes
- Guestimated standard properties size (for strings assumed size is 256 bytes) in bytes
- Additional 10% to take into consideration serialization and internals added by ASB upon sending
**Some stats**
Sending a message with a specific payload, with added standard NSB headers, and _no_ exception headers led to the following results:
| Single Payload Size   |.Size   | .EstimatedSize  | Increase |
|---|---:|---:|:---:|
|0K  | 1,474  | 3,232 | 119% |
|1K   | 2,807  | 4,754 | 69% |
| 10K  | 15,147  | 18,271 | 20% |
| 100K  | 137,977  | 153,439 | 11% |
| 170K  | 233,550  | 258,568 | 11% |
Based on the …
> Batching based on estimated message size

- packaging/nuget/nservicebus.azureservicebus.nuspec
- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1564/Routing/When_publishing_to_scaled_out_subscribers_on_multicast_transports.cs
- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Routing/When_subscribing_to_a_derived_polymorphic_event_with_forwarding_topology.cs
- src/Tests/Topology/Sending/When_sending_through_ForwardingTopology.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Events should be published to a single topic in the bundle when `ForwardingTopology` is used.
Randomly selecting topic.
Went with the following assumptions:
1. For sends it doesn't matter, throughput limit is applied on the entire namespace level (check with ASB team)
1. Bundles should default to a single topic for simplicity
1. On the sending side: active topic in a bundle is selected randomly
1. On the receiving side: receive from all topics in the bundle
Addresses issue #53
> Polymorphic events with forwarding topology

- src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
The test was passing because message was DLQed after exhausting maximum number of delivery counts and not because it was DLQ-ed by our code. By handling correct exception and fixing the test the code now tests for the right scenario.
Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/90
> Bug with native deadlettering poisonous messages - wrong exception handling

- src/Transport/Seam/MessagePump.cs
An endpoint has multiple pumps. When a pump is failing and a `RepeatedFailuresOverTimeCircuitBreaker` is raised, from a log file it's not clear which pump has actually caused the failure.
Connect to #126
> Input queue name added to circuit breaker

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/ConnectionStringValue.cs
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/PreStartupChecks/When_all_pre_startup_checks_for_forwarding_topology_fail.cs
- src/Tests/PreStartupChecks/When_execute_manage_rights_startup_check.cs
- src/Tests/Sending/When_batching_TransportOperations.cs
- src/Tests/Topology/MetaModel/When_configuring_namespace_configurations.cs
- src/Tests/Topology/MetaModel/When_configuring_namespace_info.cs
- src/Tests/Topology/MetaModel/When_configuring_namespaces_definition.cs
- src/Tests/Topology/MetaModel/When_parsing_string_to_connection_string.cs
- src/Transport/Topology/MetaModel/ConnectionString.cs
- src/Transport/Topology/MetaModel/NamespaceConfigurations.cs
- src/Transport/Topology/MetaModel/NamespaceInfo.cs
Crossposting comment from issue: what about adding two namespaces with different names and the same connection string?
@Particular/azure-maintainers ready to review
Connects to #135
> Namespace API registration with case insensitive equality check on Name property

- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusMessageReceiverSettings.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- Validates AutoRenewTimeout of OnMessage API works
- Fixes the issue where messages with completed callbacks where not marked as completed and removed from the queue (we didn't discover this because switched from manual completion to auto-completion, but queues were removed at the end of tests).
Connect to #146 
> Verify AutoRenewTimeout works as it shood

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Config/ExtensionPoints/AzureServiceBusTopologySettings.cs
- src/Transport/Topology/ITopology.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
- src/Transport/Topology/Topologies/ForwardingTopology.cs
Improved design changing _if_ check over type with a more OOP approach 
@Particular/azure-maintainers
> Remove _if_ check over topology type during configuration

- src/Tests/Addressing/Sanitization/When_sanitizing_entity_names_by_adjusting.cs
- src/Tests/Addressing/Sanitization/When_sanitizing_entity_names_by_adjusting_to_v6.cs
- src/Transport/Addressing/Sanitization/Strategies/AdjustmentSanitization.cs
- src/Transport/Addressing/Sanitization/Strategies/AdjustmentSanitizationV6.cs
Connects to #156 
Sanitization strategies didn't work with composed entity path like `queueName@connectionString` or `queueName@namespaceName`.
New implementation splits `queueName` and `suffix`, then it sanitizes only `queueName`
@Particular/azure-maintainers ready to review
> Sanitize "composed" entityPath

- CONTRIBUTING.md
Connects to #184 
Since repo has another "tests" project (`NServiceBus.AzureServiceBus.Tests`) that needs environment variables setup (`AzureServiceBus.ConnectionString` and `AzureServiceBus.ConnectionString.Fallback`), does make sense to create a section to describe this steps too?
@Particular/azure-service-bus-maintainers take a look here
> Added section with steps to setup ATTs

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Addressing/Composition/When_using_hierarchy_composition_strategy.cs
- src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs
- src/Transport/Addressing/Validation/Strategies/EntityNameValidationRules.cs
- src/Transport/Addressing/Validation/Strategies/EntityNameValidationV6Rules.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusCompositionExtensionPoint.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusCompositionSettings.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusHierarchyCompositionSettingsExtensions.cs
- src/Transport/Config/WellKnownConfigurationKeys.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Topology/MetaModel/EntityType.cs
`HierarchyComposition` should not be applied on entities of a rule type. Also, there was no way to set path generator, which rendered this strategy useless.
fixes #190 - allow to set path generator
fixes #222 - `EntityType.EventHub` is not used
> HierarchyComposition fixes

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Connectivity/When_creating_message_receivers.cs
- src/Tests/Connectivity/When_managing_client_entity_lifecycle.cs
- src/Transport/Connectivity/IMessageReceiver.cs
- src/Transport/Connectivity/MessageReceiverAdapter.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Utils/MessageReceiverExtensions.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/718
~~A spike for~~ Solves #212.
(related PRs: #223) 
Using ~~`ConcurrentQueue<Guid>`~~ `ConcurrentStack<Guid>` to store incoming message lock tokens for a batched completion.
Batched completion is taking place on a separate task. The task is backing off (delay) by 0.5 second if there's nothing to complete. Upon notifier stop, operation is blocked until all lock tokens have been completed.
**Things to consider**
The original implementation was using `await message.SafeCompleteAsync().ConfigureAwait(false);`. `SafeCompleteAsync() was logging exceptions _per message_. This is no longer an option with batched completion. Exception will be logged per batch of lock tokens (ie no message IDs.) …
> Batched completion

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/packages.config
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/packages.config
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/packages.config
- ASB 3.2.1
* Improved information in exception tracking in NamespaceManager to show namespace information in system tracker.
* Fix for a bug in all OnMessage pump api where a rare race condition can lead to ObjectDisposedException being thrown from the pump when processing callback takes too long.
*  Fixed for a bug in the WebSocket implementation where the underlying connection is not recreated in some case when keep-alive signal is not sent.
- Janitor.Fody
- GitVersionTask
> Dependencies upgrade

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Addressing/Sanitization/When_sanitizing_entity_names_by_adjusting_to_v6.cs
- src/Tests/Addressing/Sanitization/When_sanitizing_entity_names_by_throwing_exception.cs
- src/Tests/Addressing/Validation/When_using_entity_validation_rules.cs
- src/Tests/Addressing/Validation/When_using_entity_validation_v6_rules.cs
- src/Tests/Configuration/When_configuring_validation.cs
- src/Transport/Addressing/AddressingLogic.cs
- src/Transport/Addressing/Sanitization/Strategies/EndpointOrientedTopologySanitization.cs
- src/Transport/Addressing/Sanitization/Strategies/ThrowOnFailingSanitization.cs
- src/Transport/Addressing/Validation/IValidationStrategy.cs
- src/Transport/Addressing/Validation/Strategies/EntityNameValidationRules.cs
- src/Transport/Addressing/Validation/Strategies/EntityNameValidationV6Rules.cs
- src/Transport/Addressing/Validation/ValidationResult.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
Connect to #230
Connect to #228 
`IValidationStrategy` to return `ValidationResult` which in turn can provide if an entity path/name is valid or not, and list reasons why it was considered invalid. Previously, reason was not clear (issue #228).
> IValidationStrategy to distinguish between errors

- src/Tests/Addressing/Sanitization/When_sanitizing_entity_names_by_adjusting_to_v6.cs
- src/Tests/Addressing/When_apply_addressing_logic.cs
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Transport/Addressing/AddressingLogic.cs
- src/Transport/Addressing/Sanitization/Strategies/EndpointOrientedTopologySanitization.cs
Connects to #235 
I solved the issue moving logic to remove possible suffix (`@something`) at the beginning of `Apply` method of `AddressingLogic`
Composition, sanitization and validation strategies have to work on entity path or name without suffix
> Fix addressing logic with composed value

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Configuration/When_configuring_connectivity.cs
- src/Tests/Configuration/When_configuring_messaging_factories.cs
- src/Tests/Configuration/When_configuring_namespace_managers.cs
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Transport/Config/ExtensionMethods/AzureServiceBusTransportExtensions.cs
- src/Transport/Config/ExtensionPoints/AzureServiceBusNamespaceManagersSettings.cs
- src/Transport/Config/WellKnownConfigurationKeys.cs
- src/Transport/Connectivity/NamespaceManagerCreator.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
extended the configuration options of namespace managers to allow the specification of token providers
relates to #276
> Namespace manager creation config options

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Routing/AzureServiceBusTransportConfigContext.cs
- src/AcceptanceTests/Routing/When_using_single_namespace.cs
- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
- src/Transport/Connectivity/NamespaceManagerCreator.cs
- src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs
- src/Transport/Topology/MetaModel/ConnectionString.cs
- src/Transport/Topology/MetaModel/PassThroughNamespaceNameToConnectionStringMapper.cs
Found a few backward compatibility issues when not using namespace names
> Ensuring backward compat after namespace naming introduction

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Seam/When_receiving_messages.cs
- src/Tests/Sending/When_batching_TransportOperations.cs
- src/Tests/Topology/Computation/When_computing_EndpointOrientedTopology.cs
- src/Tests/Topology/Computation/When_computing_ForwardingTopology.cs
- src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs
- src/Transport/Seam/MessagePump.cs
- src/Transport/Seam/TransportResourcesCreator.cs
- src/Transport/Topology/ITopologySectionManager.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/283
- Changes `TransportResourcesCreator` and `ITopologySectionManager`s (`EndpointOrientedTopologySectionManager` and `ForwardingTopologySectionManager`) to use `QueueBindings` passed in by core into the  `TransportResourceCreator` (`IQueueCreator`)
- Eliminates the need to cheque if `QueueBindings` are defined in the settings
Remaining question - how the `identity` (string) passed into the `IQueueCreator` should be used? Should we resolve it as part of this issue or open a new one?
@danielmarbach I sense we might need a help from the core to understand the remaining issue. Thanks.
> Use QueueBindings provided by TransportResourcesCreator (ICreateQueues)

- src/Tests/Receiving/AsyncAutoResetEvent.cs
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
- src/Tests/Receiving/When_receiving_brokeredmessages_from_queues.cs
- src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
- src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
- src/Tests/Seam/When_receiving_messages.cs
- src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs
- src/Transport/Utils/TaskEx.cs
Refactored the AsyncAutoResetEvent to support cancellation. All tests that are using that event will now automatically cancel after 60 seconds when the event was not received. Will make sure the tests don't hang indefinitely.
I didn't bother to cleanup more. Arguably those tests could be structured better. The timeout could be controlled in a single place but I think this is outside of the scope of this improvement. 
@Particular/azure-service-bus-maintainers please review and merge
> AsyncAutoResetEvent supports now cancellation

- src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs
- src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
- src/Tests/Topology/MetaModel/When_mapping_connection_string_to_namespace_name.cs
- src/Tests/Topology/MetaModel/When_mapping_namespace_name_to_connection_string.cs
- src/Transport/Addressing/AddressingLogic.cs
- src/Transport/Receiving/DefaultBrokeredMessagesToIncomingMessagesConverter.cs
- src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs
- src/Transport/Topology/MetaModel/EntityAddress.cs
- src/Transport/Topology/MetaModel/PassThroughNamespaceNameToConnectionStringMapper.cs
* Removed the implicit conversation operators since to lead to unnecessary string allocations. In on one of the tests it even created a side effect because a string was compared to `EntityAddress` with `!=` and the type was boxed to a string and then the string equality was used. Call `ToString` when you need it.
* Removed computed properties and only parse it once and cache the results
* Made it a struct. Currently, it is 24 bytes which is slightly larger than the recommended struct size of 16 bytes but since this type is used during runtime this tradeoff is OK (confirmed with @Scooletz )
While doing this I think I found a bug in the mapping code. Will raise another PR.
> EntityAddress improvements

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Seam/When_dispatching_messages.cs
- src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs
- src/Transport/Receiving/BrokeredMessageReceiveContext.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Receiving/ReceiveContext.cs
- src/Transport/Seam/Dispatcher.cs
Proposal to simplify the dispatching logic.
* Avoid unnecessary closure allocations over the ReceiveContext Completed list
* Aligns with other transports
* Fixes a bug where failing service bus operations of DispatchConsistency.Default would not be passed into recoverability (old seam)
Commented out tests which would need to be rewritten
> [WIP] Batcher

- src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/292
1. Remove hardcoded queue name
1. Receive message outside of `.Done()` in a non-blocking fashion
> Do not block in Done block

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Connectivity/When_creating_message_senders.cs
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Tests/Sending/When_comparing_performance_between_built_in_batching_and_manual.cs
- src/Tests/Sending/When_retrying_on_throttle.cs
- src/Transport/Connectivity/IMessageSender.cs
- src/Transport/Connectivity/MessageSenderAdapter.cs
- src/Transport/Receiving/BrokeredMessageReceiveContext.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Sending/DefaultOutgoingBatchRouter.cs
The approach suggest by @danielmarbach  works as follows
- wrap pipeline invocation in transaction scope if SendAtomicReceive mode, so that scope flows through the pipeline into the dispatcher
- insert suppress transaction scope in the stage branch of TransportReceiveToPhysicalMessageProcessingConnector (first element in stage before ExecuteUnitOfWork), so that transaction does not flow into the handlers or persisters, but it does flow into the fork section of the connector.
- put a suppress scope around sends that do not involve send via (immediate dispatch, cross namespace routes, failover attempts, etc...)
- complete brokered message in the transaction scope around the pipeline invocation (do not a to add it to the batch)
Open question: does it work with transactional persister (f.e. …
> Send via scope approach

- src/Transport/Receiving/MessageReceiverNotifier.cs
Currently logging non-transient and transient exceptions with INFO threshold.
With the change log
* Transient exception with DEBUG threshold with full exception
* Non-transient exception with INFO threshold with message only
> Lower noise when transient exceptions occur with OnMessage callback

- src/Transport/Config/AzureServiceBusTransport.cs
- src/Transport/Config/TransactionModeSettingsExtensions.cs
- src/Transport/Connectivity/MessageReceiverCreator.cs
Connects to #340 
When transport transaction mode is None or receive mode is ReceiveAndDelete, `PrefetchCount` should not be set, unless explicitly configured by  user code.
> Control prefetch count

- src/Transport/Config/AzureServiceBusTransport.cs
Fixes #352 
When Outbox is enabled, transport transaction mode is set as the [default setting](https://github.com/Particular/NServiceBus/blob/d061342e8ed69da242514a03e9ca9ce1f96db373/src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs#L20). ASB transport was expecting to find an explicit value instead. As a result of that, the setting was ignored and the mode was not lowered as expected.
> Outbox bug issue

- src/Transport/Receiving/MessageReceiverNotifier.cs
This is a proposal PR based on my limited understanding of ASB, related to https://github.com/Particular/NServiceBus/issues/4169. This doesn't have to be merged for this release since it is not really critical.
While analyzing the code with @tmasternak we came to following conclusions:
* You can only close the internal receiver after all pending receives are completed or failed but
* The azure SDK has no way of removing the callback function OnMessage which means while shutting down messages that are prefetched and potentially more messages will still invoke the `ProcessMessageAsync` as well as add tasks to the to the `pipelineInvocationTasks` dictionary. 
* If we use `ReceiveMode.ReceiveAndDelete` calling `AbandonInternal` has no effect
* If we use `ReceiveMode.PeekLock` we are trying to …
> MessageReceiverNotifier should not invoke recoverability when receiving

- src/Transport/Config/DefaultConfigurationValues.cs
Settings safe for `AtomicSendsWithReceive` mode.
> Switching defaults for safe Atomic settings

- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Seam/MessagePump.cs
Any user specifying concurrency limit on NServiceBus endpoint and number of client per entity for Azure Service Bus transport.
When concurrency limit was lower then number of clients, concurrency could be set to zero and result in exception.
> Concurrency set to zero

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Topology/IStoppableTopology.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
- src/Transport/Topology/Topologies/ForwardingTopology.cs
- src/Transport/Topology/TopologyOperator.cs
Replaces https://github.com/Particular/NServiceBus.AzureServiceBus/pull/377/files
Closes #337
Closes #381
This PR takes @SeanFeldman changes from the above PR and brings them into hotfix-7.0.2 branch. The trade off is the following:
The stoppable topology interface is made internal. Inheriting internal interfaces on public types is a-non breaking change. The infrastructure checks whether the topology implements this internal type and then calls stop on it, if not it is a no-op.
This allows us to hotfix it since the object disposed bug can be reproduced with any of our samples out there. The downside of this is that any customer implementing a custom topology will potentially "leak" message factories. For cloud hosted scenarios outside the samples this is probably not a big deal since …
> Close message factories once and fix race on internal receivers

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Topology/IStoppableTopology.cs
- Anyone implementing a custom topology with Azure Service Bus
- `ForwardingTopology` and `EndpointOrientedTopology` introduced `Stop()` in a hotfix w/o a taking into consideration custom topologies. Therefore, custom topologies 
In version 7.0.2 both topologies introduced a public `Stop()` method which was a breaking SemVer change. In case a topology has special needs when a transport is stopping, there should be a contract to allow so. As `ITopology` cannot be modified until the next major, `IStoppableTopology` is introduced to allow the required behaviour.
> Make IStoppableTopology public

- src/Transport/Connectivity/MessagingFactoryCreator.cs
Closes #389 
* Assigns the batch flush interval for SMB and or AMQP depending on the transport type
* Reduces the runtime access to settings
* Applies reformat as discussed as a dedicated commit for simplified reviewing
> Applying batch flush interval for AMQP

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Connectivity/When_managing_namespace_manager_lifecycle.cs
- src/Tests/Creation/When_creating_forwarding_subscription.cs
- src/Tests/Creation/When_creating_subscription.cs
- src/Transport/Connectivity/INamespaceManager.cs
- src/Transport/Connectivity/NamespaceManagerAdapter.cs
- src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
- src/Transport/Creation/ICreateAzureServiceBusSubscriptions.cs
- src/Transport/Seam/SubscriptionManager.cs
- src/Transport/Topology/ICreateTopology.cs
- src/Transport/Topology/TopologyCreator.cs
Fixes #392
To implement unsubscribe functionality, 3 internal contracts were added to avoid public API changes (additions) which will be internalized in 7.1.0:
```diff
public interface ICreateTopologyAbleToDeleteSubscriptions
{
+  System.Threading.Tasks.Task TearDownSubscription(NServiceBus.Transport.AzureServiceBus.TopologySection topologySection);
}
public interface INamespaceManagerAbleToDeleteSubscriptions
{
+  DeleteSubscription(Microsoft.ServiceBus.Messaging.SubscriptionDescription subscriptionDescription);
}      
public interface ICreateAzureServiceBusSubscriptionsAbleToDeleteSubscriptions
{
+  System.Threading.Tasks.Task DeleteSubscription(string topicPath, string subscriptionName, NServiceBus.Transport.AzureServiceBus.SubscriptionMetadata metadata, string sqlFilter, …
```
> Fix unsubscribe

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Topology/MetaModel/RuntimeNamespaceInfo.cs
If `RuntimeNamespaceInfo` is internalized, no custom partitioning strategy can be created.
Creating custom partitioning strategies should still be allowed in version 7.1.0
> RuntimeNamespaceInfo should not be internal

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Topology/MetaModel/RuntimeNamespaceInfo.cs
- src/Transport/Topology/TopologyOperator.cs
When RefCount is one we would just decrease the RefCount but not shutdown.
This will make sure we shut down when all references are gone.
> Shutdown notifier when all references are gone

- src/Tests/Addressing/NamespacePartitioning/When_using_failover_namespace_strategy.cs
- src/Tests/Topology/Sending/When_sending_through_EndpointOrientedTopology.cs
- src/Tests/Topology/Sending/When_sending_through_ForwardingTopology.cs
- src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Partially addresses issue #406.
Discussed by @Particular/azure-service-bus-maintainers on a call ([summary](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/406#issuecomment-258554790))
- Section managers incorrectly filtering out passive namespaces for partitioned sends. Section managers were filtering out namespaces when should not have. 
- FailOverNamespacePartitioning returns incorrect values. Regardless of the partitioning intent, all namespaces should have been returned.
This PR does **not** address the issue with not failing over on incoming message error. That should be a separate PR.
> Namespace managers and FailOverNamespacePartitioning fixes

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Seam/When_purge_on_startup_is_enabled.cs
- src/Tests/Seam/When_receiving_messages.cs
- src/Transport/Addressing/Partitioning/IPerformNamespacePartitioningFailOver.cs
- src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/Seam/MessagePump.cs
This PR was branched of PR #415 as it depends on the fixes from #415.
Both PRs together address bug #406.
When a `FailOverNamespacePartitioning` strategy is used, message pump will instruct the strategy to fail over to the passive namespace if error reported by OnMessage API (ASB client) while using the primary namespace.
> Failing over on incoming message error

- src/Transport/Sending/DefaultOutgoingBatchRouter.cs
As part of the fix for issue #406 in PR #415 (Namespace managers and FailOverNamespacePartitioning fixes), section managers ([`EndpointOrientedTopologySectionManager`](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/415/commits/6364a832b5b12f4f23c12963fe2573229320bd39#diff-7ccd1556a44585057aa61f115e9cb3a4R138) and [`ForwardingTopologySectionManager`](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/415/commits/6364a832b5b12f4f23c12963fe2573229320bd39#diff-a135cb6bf20a8a4e627120877fbb9833R160)) were fixed to return _all_ namespaces w/o filtering out passive ones. This has introduces a problem for `DefaultOutgoingBatchRouter` as it was supposed to attempt sending messages over active namespaces first, and only if that fails, to try fallback namespaces (passive …
> Message routing - use active namespaces first

- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Topology/TopologyOperator.cs
Let's first review and squash #430 branch before we merge this in.
Closes #433 
* Shutdown notifier when all references are gone #409 
* Using dedicated OnMessageOptions per receiver #408 
* Guard the `OptionsOnExceptionReceived `with a try / catch to not throw to the SDK
* `OptionsOnExceptionReceived ` made async void because we don't want to hold up the SDK calls when we invoke the error callback
* Even when core instructed the transport to do an immediate retry we triggered before the errorCallback. This was not an issue since the error callback was not properly wired. With the changes introduced in #430 this would become a problem. We now only trigger the error callback when we are receiving a callback from the SDK in `OptionsOnExceptionReceived ` or when we could execute the …
> Shutdown race

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Topology/MetaModel/NamespaceConfigurations.cs
- src/Transport/Topology/MetaModel/NamespaceInfo.cs
Closes #404 
For more details see the issue for details
> Types used for namespace partitioning are no longer obsoleted

- src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs
This branch is an attempt to test the router and invocation of namespaces without going through the actual ASB.
`Should_route_via_active_namespace_first` -> `Should_route_via_active_namespace_first_no_ASB_required`
`Can_route_via_fallback_namespace` -> `Can_route_via_fallback_namespace_no_ASB_required`
Original tests used ASB broker. As a result of that, tests could be flaky and not necessarily verify the behavior. Alternative is to stub out invokation of ASB and deterministically identify if the right namespace is used based on input criteria. 
@Particular/azure-service-bus-maintainers what do you think?
> Testing router without actual asb namespaces

- src/Transport/Topology/ITopology.cs
- src/Transport/obsoletes.cs
Moving into `obsolete.cs` rather than keeping with `ITopologyInternal`
> Move the ObsoleteMessages where it belongs

- src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
- src/Transport/Topology/Topologies/ForwardingTopology.cs
Small step towards https://github.com/Particular/NServiceBus.AzureServiceBus/issues/448
Removes `NamespaceManagerCreator ` from the container
> NamespaceManagerCreator is no longer on the container

- src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
- src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
- src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
- src/Transport/Topology/Topologies/ForwardingTopology.cs
Small step towards https://github.com/Particular/NServiceBus.AzureServiceBus/issues/448
- MessagingFactoryCreator is no longer registered on the container
- MessagingFactoryLifeCycleManager still is for resolving but is owned by the topology
> No longer registering MessagingFactoryLifeCycleManager and MessagingFactoryCreator on the container

- src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Routing/When_subscribing_to_a_derived_polymorphic_event_with_forwarding_topology.cs
- src/AcceptanceTests/Routing/When_unsubscribing.cs
- src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
- Anyone that requires to be able to unsubscribe endpoints from events and using `EndpointOrientedTopology`
Unsubscribe requests are not persisted, causing unsubscribed endpoints continue receiving events after those endpoints were restarts.
Similar to the issue that was found in `ForwardingTopology` (#392).
The request to unsubscribe should be modifying topologies. [Currently](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e5f64e929ecf7ff2227541870ae9a2c243ed9222/src/Transport/Seam/SubscriptionManager.cs#L28) it doesn't.
For the `EndpointOrientedTopology`, subscriber should remove the subscription from the publisher.events topic.
This could cause events to accumulate under subscription that is no longer monitored. If there's a high volume of these events, subscription …
> Subscription not removed when unsubscribing with EndpointOrientedTopology

- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Transport/Topology/MetaModel/EntityInfo.cs
- src/Transport/Topology/MetaModel/SubscriptionInfo.cs
This is just a small backwards compatible cleanup to perform subscription related comparison in `SubscriptionInfo` and not `EntityInfo`.
There's an issue with our entities abstraction and some features introduced in v7. I'll open a separate issue for that.
> Keep SubscriptionIfo comparison out of EntityInfo

- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0/Routing/NativePublishSubscribe/When_multi_subscribing_to_a_polymorphic_event.cs
- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Transport/Topology/MetaModel/EntityInfo.cs
- src/Transport/Topology/MetaModel/SubscriptionInfo.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
Fixes #460 (Polymorphic events from different publishers not handled properly with `EndpointOrientedTopology`).
Based on the changes made in [`entity-info` branch](https://github.com/Particular/NServiceBus.AzureServiceBus/tree/entity-info).
Details and description are in the original issue.
> Events hierarchy from different publishers with EndpointOrientedTopology not handled

- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0/Routing/NativePublishSubscribe/When_multi_subscribing_to_a_polymorphic_event.cs
- src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Topology/MetaModel/SubscriptionInfo.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- Anyone using `EndpointOrientedTopology` and has endpoints that subscribe to polymorphic events published by different endpoints, applying workaround demonstrated in [Polymorphic events with Azure Service Bus Transport](https://docs.particular.net/samples/azure/polymorphic-events-asb/) sample.
Each publisher should have a subscription for the subscriber, but only one such subscription is created under a single publisher. This could lead to published events disappear and never be handled. While `EndpointOrientedTopology` doesn't support polymorphic events out-of-the-box, with disabled `AutoSubscribe` feature and manual subscription to the base event it should work as expected.
Verification `When_multi_subscribing_to_a_polymorphic_event` should work for this scenario when `AutoSubscribe` …
> Backport issue 460 to 7.0.5

- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0/Routing/NativePublishSubscribe/When_multi_subscribing_to_a_polymorphic_event.cs
- src/Transport/Topology/MetaModel/SubscriptionInfo.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
Events hierarchy from different publishers with EndpointOrientedTopology not handled ( #460)
Fix has been applied to `hotfix-7.1.1` and `hotfix-7.0.5`.
> Porting fix to issue 460 to develop

- src/NServiceBus.AzureServiceBus.sln.DotSettings
- src/Transport/AzureServiceBusTransport.cs
This PR sets the default transaction isolation level to serializable by default instead of fixed. This allows users to override it if their scenario has different needs.
> allow setting isolation level

- src/Tests/Creation/When_creating_forwarding_subscription.cs
- src/Tests/Creation/When_creating_subscription.cs
- src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
Fixes #487 
Anyone using Azure Service Bus transport and using a namespace partitioning strategy that creates the same subscription in multiple namespaces including the built-in strategies [Round Robin](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#round-robin-namespace-partitioning) and [Fail over](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#fail-over-namespace-partitioning).
When using multiple namespaces NServiceBus throws a `MessagingEntityNotFoundException` exception during startup.
> Subscription fails on multiple namespaces

- src/Tests/Creation/When_creating_forwarding_subscription.cs
- src/Tests/Creation/When_creating_subscription.cs
- src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
Backport of #489 to Support-7.0
Anyone using Azure Service Bus transport and using a namespace partitioning strategy that creates the same subscription in multiple namespaces including the built-in strategies [Round Robin](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#round-robin-namespace-partitioning) and [Fail over](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#fail-over-namespace-partitioning).
When using multiple namespaces NServiceBus throws a `MessagingEntityNotFoundException` exception during startup.
> Subscription fails on multiple namespaces (#489)

- src/Tests/Creation/When_creating_queues.cs
- src/Tests/Creation/When_creating_topics.cs
- src/Transport/Creation/AzureServiceBusQueueCreator.cs
- src/Transport/Creation/AzureServiceBusTopicCreator.cs
Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/508
On startup the transport will attempt to create the entity (queue or topic) if it does not exist.
Some entity properties may only be set at creation time and may not be modified later (immutable).
This PR corrects an issue where the endpoint configuration might describe an entity in such a way that it is different from the existing entity, and includes changes to both mutable and immutable properties.  The previous behavior would attempt to modify all properties to match the endpoint configuration, which would be rejected by ASB with a 400 error.  The new behavior is to copy the value of existing, immutable properties from the existing entity into the requested entity for update.  This will eliminate the …
> Safe entity update (#508)

- src/Tests/Creation/When_creating_subscription.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/508
`RequiresSession` is a read-only/immutable property for subscriptions that should not be changed.
> Safe subscriptions update

- src/Tests/Creation/When_creating_queues.cs
- src/Tests/Creation/When_creating_subscription.cs
- src/Tests/Creation/When_creating_topics.cs
- src/Transport/Creation/AzureServiceBusQueueCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusTopicCreator.cs
- Anyone using Azure Service Bus 7.0 and up and performing entity updates that include immutable properties (`RequiresDuplicateDetection`, `EnablePartitioning`, `RequiresSession`).
- The transport fails to update the entities.
Issue #508
> Hotfix 7.0.8

- src/Tests/Creation/When_creating_queues.cs
- src/Tests/Creation/When_creating_subscription.cs
- src/Tests/Creation/When_creating_topics.cs
- src/Transport/Creation/AzureServiceBusQueueCreator.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
- src/Transport/Creation/AzureServiceBusTopicCreator.cs
- Anyone using Azure Service Bus 7.1 and up and performing entity updates that include immutable properties (`RequiresDuplicateDetection`, `EnablePartitioning`, `RequiresSession`).
- The transport fails to update the entities.
Issue #508
> Hotfix 7.1.5

- packaging/nuget/nservicebus.azureservicebus.nuspec
- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/packages.config
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/packages.config
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/Transport/packages.config
- src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
- src/TransportTests/packages.config
Connects to #514
- Anyone using Azure Service Bus and required to use `WindowsAzure.ServiceBus` version 4.0.0
No symptoms. This release is is to support the latest version of the `WindowsAzure.ServiceBus` library version 4.0.0
> ASB 4.0.0 dependency update

- src/Transport/Sending/DefaultOutgoingBatchRouter.cs
Small fix in the logs, we are logging that we would use send via even if the tx mode is set to receive only. We don't effectively do, so the log is misleading
> should not log that we would use send via if we don't

- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.2.0/DelayedDelivery/When_Deferring_a_message.cs
- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.2.0/DelayedDelivery/When_deferring_to_non_local.cs
- src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.2.0/Routing/When_publishing_an_event_implementing_two_unrelated_interfaces.cs
- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_incoming_message_lock_token_is_lost_in_send_atomic_with_receive_mode.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Utils/TaskEx.cs
Connects to #532 
Critical hotfix to address outgoing duplicates created in `SendsAtomicWithReceive` transport transaction mode.
> Hotfix 7.2.1

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_incoming_message_lock_token_is_lost_in_send_atomic_with_receive_mode.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Utils/TaskEx.cs
Connected to #532 
Backport of `hotfix-7.2.1`
Related to #530 
Anyone using Azure Service Bus transport with `SendsAtomicWithReceive` transaction guarantee
Incoming message is processed, **not** completed (a warning about message lost lock is logged), but the outgoing messages are dispatched.
As a result of that, incoming message is re-processed, causing outgoing messages to be sent again, generating duplicates.
> Hotfix 7.1.6

- src/AcceptanceTests/Infrastructure/TestIndependenceBehavior.cs
Skip message earlier if message is not part of the current acceptance test run.
`ITransportReceiveContext` behavior is executed prior to `IIncomingPhysicalMessageContext`.
@danielmarbach also using `IBehavior` instead of `Behavior<T>` as per discussion with @bording
> TestIndependenceSkipBehavior improvement

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_receive_operation_is_aborted.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
Replaces PR #544 
Connects to #542 (Message is completed instead of abandoned when incoming message processing is aborted)
This fix should ensure that the edge case is covered and there's no chance we'd generate duplicates when we shouldn't.
@yvesgoeleven & @danielmarbach you've already reviewed this, but please have a look again to make sure everything is there.
@Particular/azure-maintainers should be released with #553 (`hotfix-7.1.7`)
> Hotfix 7.2.2

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_receive_operation_is_aborted.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
Connects to #542 (Message is completed instead of abandoned when incoming message processing is aborted)
Anyone using Azure Service Bus transport with `SendsAtomicWithReceive` transaction guarantee and implements a custom behavior `Behavior<ITransportReceiveContext>` to cancel incoming message processing by invoking `context.AbortReceiveOperation();`.
Custom behavior requests incoming message processing to be aborted.  Incoming message is successfully aborted, but the outgoing messages are still dispatched. 
---
@Particular/azure-maintainers please review. Should be released with #552 (`hotfix-7.2.2`)
> Hotfix 7.1.7

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/Receiving/When_receive_operation_is_aborted.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
Connects to #542 (Message is completed instead of abandoned when incoming message processing is aborted)
This fix should ensure that the edge case is covered and there's no chance we'd generate duplicates when we shouldn't.
@Particular/azure-maintainers should be merged _after_ #553 (`hotfix-7.1.7`) and #552 (`hotfix-7.2.2`) are merged.
> Porting fixes from #542 to develop

- src/Transport/Connectivity/MessageReceiverCreator.cs
- src/Transport/Connectivity/MessageSenderCreator.cs
- src/Transport/Connectivity/NamespaceManagerCreator.cs
No longer use settings at runtime in components under connectivity. Shows a simple approach which can be followed. Basically each class that is used during runtime with a field of type `ReadonlySettings `is probably abusing the settings
> Components in Connectivity no longer use settings at runtime

- src/Tests/Addressing/Individualization/When_using_discriminator_individualization_strategy.cs
- src/Tests/NServiceBus.Azure.Transports.WindowsAzureServiceBus.approved.cs
- src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs
- src/Transport/Addressing/Individualization/Strategies/DiscriminatorBasedIndividualization.cs
- src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
- src/Transport/Addressing/Partitioning/Strategies/SingleNamespacePartitioning.cs
- src/Transport/Addressing/Sanitization/Strategies/ThrowOnFailedValidation.cs
- src/Transport/Addressing/Sanitization/Strategies/ValidateAndHashIfNeeded.cs
- src/Transport/Addressing/Sanitization/ValidationResult.cs
Replaces #601 
Ports all the optimizations over but still relies on ctor injection in the strategies. Gives the benefit of no longer relying on settings during runtime but is not invasive. So no doco changes are required.
> Strategies use readonly settings in ctor only and are optimized for fewer allocs

- src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
- src/Transport/Sending/BatchedOperationsToBrokeredMessagesConverter.cs
- src/Transport/Sending/OutgoingBatchRouter.cs
Connects to #282 
No longer relying on `ReadOnlySettings` during runtime.
> Remove ReadOnlySettings from sending runtime

- src/Tests/PreStartupChecks/When_execute_manage_rights_startup_check.cs
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
- src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Receiving/MessageReceiverNotifierSettings.cs
- src/Transport/Topology/MetaModel/DefaultConnectionStringToNamespaceAliasMapper.cs
- src/Transport/Topology/MetaModel/ManageRightsCheck.cs
- src/Transport/Topology/TopologyCreator.cs
- src/Transport/Topology/TopologyOperator.cs
Connects to #282 
- No longer relying on `ReadOnlySettings` during runtime for topology related code.
- Modified `MessageReceiveNotifier` not to need `ReadOnlySettings` (replaced with `MessageReceiveNotifierSettings`).
> Remove readonly settings from topology related code

- src/Tests/Connectivity/When_managing_client_entity_lifecycle.cs
- src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
- src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
- src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Sending/When_comparing_performance_between_built_in_batching_and_manual.cs
- src/Transport/Connectivity/MessageReceiverLifeCycleManager.cs
- src/Transport/Connectivity/MessageSenderLifeCycleManager.cs
- src/Transport/Receiving/INotifyIncomingMessages.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Seam/MessagePump.cs
- src/Transport/Sending/OutgoingBatchRouter.cs
- src/Transport/Topology/IOperateTopology.cs
- src/Transport/Topology/TopologyOperator.cs
- MessageReceiverNotifier no longer used a blocking start
- Concurrent acquire of entities
- Asynchronous Message[Sender|Receiver]LifeCycleManager
Before :
- (Default 5): 3542 / 3549
- (10): 2935 / 2974
- (20): 3079 / 3195
- (50): 3516 / 3212
After:
- (Default 5): 2678 / 2667
- (10): 2501 / 2384
- (20): 2512 / 2355
- (50): 2560/ 2558
``` ini
BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4980HQ CPU 2.80GHz, ProcessorCount=8
Frequency=2728072 Hz, Resolution=366.5592 ns, Timer=TSC
[Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.7.2102.0
DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.7.2102.0
```
Method | IsClosed |        Mean |    StdErr |     StdDev |         Min |          Q1 |      Median |          Q3 |         Max |     Op/s | …
> MessageReceiverNotifier non-blocking start

- src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
@yvesgoeleven 
This will fix the `When_publishing_with_overridden_local_address` failing test on `EndpointOrientedTopology`.
> New core ATT requires publisher registration

- src/Tests/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/Config/ExtensionPoints/AzureServiceBusNamespaceRoutingSettings.cs
- src/Transport/Topology/MetaModel/NamespaceConfigurations.cs
- src/Transport/Topology/MetaModel/NamespaceInfo.cs
API draft to solve #585 and #584 
- `AddNamespace `on routing will return a `NamespaceInfo  `since that class is already public
- `NamespaceInfo `has been extended to have a property called `RegisteredEndpoints `which allows indicating that an endpoint belongs to the specific namespace
- Uses a HashSet with ordinal ignore case comparison to avoid having duplicate entries in the set
> RegisteredEndpoints can be added to the namespace info

- src/AcceptanceTests/Routing/When_sending_to_specific_namespace.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Based on #622 
Closes #585 
Doco https://github.com/Particular/docs.particular.net/pull/3276
`DetermineSendDestination` is the central location where either explicit destinations with alias or connection string or endpoint names will go through. The routing has been extended to look up whether a registered endpoint is available and then use that as a destination. If no registered endpoint is available the normal partitioning strategy approach will be used. 
The assumptions are that if a destination contains `@alias` or `@connectionstring` the `inputQueueAddress` will have the properties set as usual and this takes precedence. For all other destinations without `@` the else part is responsible.
> Send over namespaces

- src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
- src/AcceptanceTests/Routing/When_sending_to_specific_namespace.cs
- src/AcceptanceTests/Routing/When_subscribing_outside_the_endpoint_oriented_topology.cs
- src/AcceptanceTests/Routing/When_using_single_namespace.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
This PR fixes cross namespace subscriptions in the endpoint oriented topology, https://github.com/Particular/NServiceBus.AzureServiceBus/issues/584
It builds on the new api, https://github.com/Particular/NServiceBus.AzureServiceBus/pull/622, that allows to register an endpoint in a namespace outside the topology using
```
extensions.NamespaceRouting()
.AddNamespace("publisherNamespace", publisherConnectionString)
.RegisteredEndpoints.Add(AcceptanceTesting.Customization.Conventions.EndpointNamingConvention(typeof(Publisher)));
```
and takes this info into account when creating subscriptions.
A test, `When_subscribing_outside_the_endpoint_oriented_topology`, was added to proof that it works
I had to change the ATT's a little bit as the configure class did overwrite whatever topology was set …
> Subscribe outside topology

- src/AcceptanceTests/Infrastructure/Cleaner.cs
- src/AcceptanceTests/Infrastructure/TestUtility.cs
Connects to #634 
Fixes #634 
Adding a single `explicit` test that should be triggered from TC build configuration step at the **after** ATTs step is done, to remove all queues and topics.
An explicit test called `DeleteEntities()` that asynchronously deletes all queues and topics on the main namespace with up to 5 retries per each entity.
1 - Additional (last) build step for EndpointOriented and Forwarding topology.
2 - Step is set to always execute .
3 - Cleaner is explicitly executed by selecting it using a filter ` --where "name==DeleteEntities && cat==Cleanup"`
4 - Assembly for Cleaner test is always `AcceptanceTests.dll`
> Cleanup test to remove all queues and topics

- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Sending/When_batching_TransportOperations.cs
- src/Tests/Topology/Computation/When_computing_EndpointOrientedTopology.cs
- src/Tests/Topology/Computation/When_computing_ForwardingTopology.cs
- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Seam/TransportResourcesCreator.cs
- src/Transport/Topology/ITopologySectionManager.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- src/Transport/Topology/Topologies/EndpointOrientedTransportInfrastructure.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Closes #625
Fixes SendOnly endpoint publish
Assuming manage rights:
- Queue creation happens during ressource creation phase
- Topic creation happens when the transport is started
> Clear separation of queues and topic creation

- src/Tests/Configuration/When_using_default_configuration.cs
- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Config/DefaultConfigurationValues.cs
Connect to #654 
Fixes #654 
Don't check serializer when setting default values, defer at a later stage of the transport Start
> Guard.AgainstUnsetSerializerSetting() should not be invoked during defaults setup

- src/AcceptanceTests/Cleaner.cs
- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/AcceptanceTests/packages.config
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Tests/packages.config
- src/Transport/Utils/ExceptionExtensions.cs
- src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
- src/TransportTests/packages.config
Connects to #659
Backport of https://github.com/Particular/NServiceBus.AzureServiceBus/pull/658
Connects to https://github.com/Particular/NServiceBus.Azure/issues/319
Anyone using NServiceBus.Azure.Transports.WindowsAzureServiceBus transport version 7 and experiencing exceptions during endpoints shutdown.
The circuit breaker might be implemented to shutdown the appdomain, which will cause a garbage collection. Message in flight handles by the transport call into the infrastructure at that point may cause the underlying SDK to attempt cleanup using objects which have already been disposed. As a result of that, endpoint logs exceptions and doesn't end cleanly.
When an endpoint is stopping and exception is thrown, we check if exception is transient or not. If exception is not transient, the …
> fix for operation cancelled exception triggering concurrent dispose

- src/Tests/Topology/MetaModel/When_parsing_string_to_connection_string.cs
- src/Transport/Topology/MetaModel/ConnectionString.cs
Related to #662 
Fixes #662
Anyone using NServiceBus.Azure.Transports.WindowsAzureServiceBus transport version 7 and needs to connect to Azure Service Bus using domain other than `servicebus.windows.net`.
Exception is thrown.
> Connection string should not check for a specific domain name

- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Tests/Seam/When_purge_on_startup_is_enabled.cs
- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Seam/MessagePump.cs
Core has introduced a change in one of the latest beta builds.
The change was related to how `Setting.LocalAddress()` is working. The transport used to set directly settings value for the `SharedQueue`. The change in Core has introduced a concept of a "Receive Component" that cannot be manipulated by the transport directly, used by `Settings.LocalAddress()` logic, and is only instantiated when the receive infrastructure is created.
Tests that were executing w/o Core starting the receive infrastructure, would fail.
- Tests that exercise `MessagePump` directly
- Transport Tests
- Any other unit test that would run `AzureServiceBusTransportInfrastructure.Start()`
This change introduced the following:
1. MessagePump is no longer accessing `Settings.LocalAddress()` directly, and instead is …
> Local address not available during tests

- src/Tests/TestApprover.cs
Simplifies the testing and makes `TestApprover` immune to shadow copying.
> Make TestApprover immune to shadow copying

- src/Tests/Topology/When_counting_existing_topics_in_bundle.cs
The bundle prefix test needs to use the artificial bundle prefix instead of bundle-1 to not count the existing bundles that remain from previous test runs
> Fix bundle prefix test

- src/AcceptanceTests/Addressing/RoundRobinPartitioningFailoverStrategy.cs
- src/AcceptanceTests/Addressing/When_publishing_message_with_custom_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_publishing_message_with_default_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_publishing_message_with_failover_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_publishing_message_with_roundrobin_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_sending_message_with_custom_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_sending_message_with_default_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_sending_message_with_failover_partitioning_strategy.cs
- src/AcceptanceTests/Addressing/When_sending_message_with_roundrobin_partitioning_strategy.cs
- src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
- src/AcceptanceTests/Infrastructure/TestUtility.cs
- src/AcceptanceTests/Routing/When_sending_to_specific_namespace.cs
- src/AcceptanceTests/Routing/When_subscribing_outside_the_endpoint_oriented_topology.cs
- src/AcceptanceTests/Routing/When_unsubscribing.cs
- src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs
- src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
- src/Tests/ApprovalFiles/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Tests/Configuration/When_configuring_namespace_partitioning.cs
- src/Tests/Topology/Topologies/When_using_SectionManager_with_RoundRobinNamespacePartitioning.cs
- src/Transport/Addressing/Partitioning/INamespacePartitioningStrategy.cs
- src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
- src/Transport/Addressing/Partitioning/Strategies/RoundRobinNamespacePartitioning.cs
- src/Transport/Addressing/Partitioning/Strategies/SingleNamespacePartitioning.cs
- src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
- src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
Fixes #672
Fixes #678
Fixes #679
This PR introduces the possibility to indicate on a namespace partitioning strategy whether the result of `GetNamespaces` can be cached for sending. The flag was named `SendingCachaeble` in order to clearly show that currently only call for `PartitioningIntent.Sending` are cached by the infrastructure. 
Verification tests to demonstrate caching issue with RoundRobin strategy in v8 #672.
> Namespace Partitioning Strategy can indicate whether caching of runtime namespaces is feasible

- src/Tests/ApprovalFiles/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
- src/Transport/obsoletes.cs
Related to #672
Related to #673
`ICacheSendingNamespaces` introduced in 7.2.10 should be obsoleted in v8.
> Obsoleting ICacheSendingNamespaces in v8

- src/AcceptanceTests/Addressing/When_sending_message_with_hierarchy_composition_strategy.cs
- src/Tests/Addressing/Composition/When_using_hierarchy_composition_strategy.cs
- src/Tests/Addressing/When_apply_addressing_logic.cs
- src/Tests/Topology/MetaModel/When_parsing_string_to_connection_string.cs
- src/Transport/Addressing/AddressingLogic.cs
- src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs
Related to #695 (https://github.com/Particular/NServiceBus.AzureServiceBus/pull/694#issuecomment-356512245)
Replaces #694
Depends on #696
**WARNING** PR #696 needs to be merged prior to this change.
Addressing logic should not operate on values that are already processed destinations such as `destination@alias` or `destination@connectionString` and can shortcut by returning the as-is.
> AddressingLogic should shortcut for addresses with suffix

- src/AcceptanceTests/Addressing/When_sending_directly_with_hierarchy_composition_and_secure_connection.cs
- src/Tests/Addressing/When_apply_addressing_logic.cs
- src/Transport/Addressing/AddressingLogic.cs
As part of #696 and #697 fix, a regression bug was introduced.
Raised this question in https://github.com/Particular/NServiceBus.AzureServiceBus/pull/694#issuecomment-356512245, but looks like it was overlooked.
The issue is when a direct send is used while using secure connection strings and `HierarchyComposistion`  using a command such as `Send("endpoint@alias`, short-cutting in `AddressingLogic` would cause to return `endpoing@alias` w/o running the address through hierarchy composition. This would cause dispatch to a non-existent destination and result in failure.
> AddressingLogic regression bug fix

- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/TransactionScopeSuppressFeature.cs
Fixes #743 
Azure Service Bus suppresses transaction scope for all transports for all transports in a multi-endpoint hosted scenario. The feature should only be enabled for ASB transport.
@Particular/azure-maintainers please review/merge (commit, no squash).
> Hotifx 8.0.3

- src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
- src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
- src/Transport/NServiceBus.AzureServiceBus.csproj
- src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
This updates development tooling on the `support-8.0` branch.
Note: It is okay for this to be squashed.
> Update development tooling

- src/AcceptanceTests/Receiving/When_messages_contains_typed_properties.cs
- src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs
Backport of #803 to `support-9.0`
> Custom header information is converted into null

- src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
Fixes #811 
- Do not create duplicate subscription.
- Log info message advising what subscriptions can be optimized by updating SQL Rule, providing an optimized filter SQL expression.
- Test to verify subscriptions are not duplicated when a previously created subscription with transport version 8 or earlier already exist.
- Automated SQL Rule optimization
> Hotfix 9.1.2

- src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
- src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
Anyone using endpoint-oriented topology with the legacy Azure Service Bus transport version 9 and above.
When a subscribing endpoint creates its subscriptions, a duplicate subscription is created for each event. While subscriber is listening to only one of those, messages in the duplicate subscription are accumulated and could cause event overflow, impacting the entire namespace performance. Eventually, this can lead to degradation and interruption of the normal service operation.
A possible workaround is to manually modify the default rule for the original subscription to match the default rule of the duplicate subscription. After doing this, the duplicate subscription can be deleted. When the endpoint restarts it will no longer create the duplicate subscription. 
_Credit: @onesadjam_ …
> Hotfix 9.0.5

- src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
- src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
- src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
- src/Transport/Receiving/INotifyIncomingMessages.cs
- src/Transport/Receiving/MessageReceiverNotifier.cs
- src/Transport/Seam/MessagePump.cs
- src/Transport/Topology/IOperateTopology.cs
- src/Transport/Topology/MetaModel/NamespaceInfo.cs
- src/Transport/Topology/TopologyOperator.cs
- src/TransportTests/ConfigureAzureServiceBusTransportInfrastructure.cs
- src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
Backport of fix from #818
Anyone using the transport.
Exceptions thrown in recoverability policy are not propagated as critical error and hide the underlying infrastructure problems that user code could be responding to.
By not properly handling exceptions when the recoverability policy throws, and not raising a critical error, the transport does not allow taking an action when the underlying messaging infrastructure is partially failing.
> Exceptions in recoverability policy do not trigger critical error

- src/Tests/Topology/Computation/When_computing_EndpointOrientedTopology.cs
- src/Tests/Topology/Computation/When_computing_ForwardingTopology.cs
These tests seem to fail because for some reason, the fake connection string that was used no longer works as the underlying SDK implementation changed.
I changed it to use the actual connection string that is available anyway, with that, the tests seem to pass.
> Fix failing topology tests

- src/AcceptanceTests/Infrastructure/TestIndependenceBehavior.cs
only discard messages that have a `TestRunId` header AND where this id doesn't match with the current test run. This prevents raw messages or control messages from being discarded although those are part of this test.
Preliminary requirement to make the additional test added through #1008 pass, as it sends a control message that doesn't go through the mutator logic in the test infrastructure that adds the necessary header.
> Don't discard unmarked messages in AcceptanceTests
