Particular/NServiceBus.AzureServiceBus

src/Tests/Creation/When_creating_subscription.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/ICreateAzureServiceBusSubscriptions.cs
src/Transport/Topology/MetaModel/EntityInfo.cs
src/Transport/Topology/Topologies/StandardTopologySectionManager.cs
src/Transport/Topology/TopologyCreator.cs

To help users make sense out of subscription names that are converted into GUIDs.
@yvesgoeleven what do you think?

storing original subscription name as metadata

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1291/Performance/ProcessingOptimizations/When_limiting_concurrency_via_both_api_and_config.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1291/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1291/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_autoSubscribe.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1291/Sagas/when_receiving_multiple_timeouts.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Topology/Topologies/StandardTopologySectionManager.cs

Fixing ATTs that fail because
1. Core ATT FW needs to be fixed/updated
2. Transport implementation needs to be fixed/updated
Don *NOT* merge this until all tests are green

Fixing acceptance tests

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/TransportEncoding/When_sending_to_an_endpoint_with_different_transport_encoding.cs
src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs
src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/DefaultBrokeredMessagesToIncomingMessagesConverter.cs
src/Transport/Sending/DefaultOutgoingMessagesToBrokeredMessagesConverter.cs
src/Transport/Utils/BrokeredMessageHeaders.cs

An attempt to implement #32 (Feature: Make it easier to work with native body content)
@Particular/azure please review

[WIP] Brokered message body interop

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1335/Sagas/When_forgetting_to_set_a_corr_property.cs
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Tests/Seam/When_receiving_messages.cs
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Receiving/ReceiveContext.cs
src/Transport/Seam/MessagePump.cs
src/Transport/packages.config

Related to Particular/NServiceBus#3254
Allowing to cancel the in flight message processing by the `CancellationTokenSource` passed via `PushContext`

Using cancellation tokens to support canceling of the receive

---

src/Transport/Connectivity/MessagingFactoryAdapter.cs
src/Transport/Connectivity/MessagingFactoryLifeCycleManager.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/Dispatcher.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Seam/SubscriptionManager.cs
src/Transport/Seam/TransportResourcesCreator.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Topology/TopologyOperator.cs
src/Transport/Utils/BrokeredMessageExtensions.cs

Nothing funny to see here @Particular/azure-maintainers :)
Connect to #94

Added ConfigureAwait(false) for awaitable operation

---

src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config

Part of https://github.com/Particular/PlatformDevelopment/issues/610

Added coderules

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Connectivity/When_managing_namespace_manager_lifecycle.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/PreStartupChecks/When_execute_manage_rights_startup_check.cs
src/Transport/Config/AzureServiceBusTransport.cs
src/Transport/Connectivity/INamespaceManager.cs
src/Transport/Connectivity/NamespaceManagerAdapter.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Topology/ITopology.cs
src/Transport/Topology/PreStartupChecks/ManageRightsCheck.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/Topologies/StandardTopology.cs

@Particular/azure-maintainers could you evaluate this new implementation?
Could be an option to open to users the possibilities to inject "pre startup checks" from configuration API or somewhere else
Connects to #96

pre startup check integration

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1423/Routing/When_distributing_an_event.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1423/Routing/When_publishing.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1423/Sagas/when_receiving_multiple_timeouts.cs
src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-unstable1423/Scheduling/When_scheduling_a_recurring_task.cs
src/AcceptanceTests/ConfigureAzureServiceBusTransport.cs
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Connectivity/When_managing_namespace_manager_lifecycle.cs
src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_subscription.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/Topology/Computation/When_computing_ForwardingTopology.cs
src/Transport/Connectivity/INamespaceManager.cs
src/Transport/Connectivity/NamespaceManagerAdapter.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
src/Transport/Creation/ICreateAzureServiceBusSubscriptions.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Topology/MetaModel/EntityInfo.cs
src/Transport/Topology/MetaModel/SubscriptionInfo.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
src/Transport/Topology/Topologies/StandardTopologySectionManager.cs
src/Transport/Topology/TopologyCreator.cs
src/Transport/Topology/TopologyOperator.cs

Issues:
Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/13

Forwarding topology pub/sub

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Configuration/When_configuring_queues.cs
src/Tests/Configuration/When_configuring_subscriptions.cs
src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_queues.cs
src/Tests/Creation/When_creating_subscription.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusQueueSettings.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusSubscriptionSettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Removing ForwadTo on Queues and Subscriptions to fix #117

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/PreStartupChecks/When_all_pre_startup_checks_for_forwarding_topology_fail.cs
src/Tests/PreStartupChecks/When_execute_manage_rights_startup_check.cs
src/Tests/PreStartupChecks/When_executing_topic_partitioning_check_for_forwarding_topology.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Topology/PreStartupChecks/ManageRightsCheck.cs
src/Transport/Topology/PreStartupChecks/TopicPartitioningCheckForForwardingTopology.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/Topologies/StandardTopology.cs

Fixes issue #131 
Connects to #92

Partitioning should not be enabled when forwarding topology is used

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/Config/AzureServiceBusTransport.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusConnectivitySettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs

Fixes #130.
- [Default mode](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/130#issuecomment-190981534) is `AutoDetect` and not `Tcp`
Connects to #92

ConnectivityMode implementation

---

src/Transport/Config/DefaultConfigurationValues.cs

Addresses issue #137 
Connects to #92

MaxDeliveryCount default value

---

src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs
src/Tests/TestUtils/ConnectionString.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
src/Transport/Topology/Topologies/StandardTopologySectionManager.cs

Implementation & tests for passive namespace fallback
Connects to #103

Passive fallback

---

src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
src/Transport/Seam/MessagePump.cs

Based on number of namespaces used by topology.
Implements #97 

Determine transport transaction mode

---

packaging/nuget/nservicebus.azureservicebus.nuspec
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/app.config
src/AcceptanceTests/packages.config
src/EnduranceTests/App.config
src/EnduranceTests/NServiceBus.AzureServiceBus.EnduranceTests.csproj
src/EnduranceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config

Upgrade ASB library to the latest 3.1.5

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Routing/When_scaling_out_senders_that_uses_callbacks.cs

Added acceptance test to verify unified callbacks in core work with ASB.
Connects to #80 
@Particular/azure-maintainers that are not me, please review :)

Callbacks verification

---

GitVersionConfig.yaml

Connects to https://github.com/Particular/PlatformDevelopment/issues/706

Switching to alpha naming scheme

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Configuration/When_configuring_queues.cs
src/Tests/Configuration/When_configuring_subscriptions.cs
src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_queues.cs
src/Tests/Creation/When_creating_subscription.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusQueueSettings.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusSubscriptionSettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Fixes #185 
Sessioned and non-sessioned messages cannot be mixed. Removing ability to enable sessions.

Remove RequiresSession

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Creation/ReadOnlySettingsExtensions.cs
src/Transport/Receiving/DefaultBrokeredMessagesToIncomingMessagesConverter.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/Dispatcher.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Sending/Batcher.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs

Few cleanups like
* Redundant, unnecessary code removed
* Unnecessary awaits removed
* Batch sending concurrently
* Proper await in OnError with CircuitBreaker

Minor tweaks

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/Sending/IConvertOutgoingMessagesToBrokeredMessages.cs

@Particular/azure-service-bus-maintainers ping!

Remove unused api to convert outgoing messages to brokered messages

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/obsoletes.cs

* AzureServiceBusQueueConfig
* BrokeredMessageConverter
* NamingConventions
Will address issues #215 and #216 

Missing obsoletes

---

src/Tests/Topology/MetaModel/When_mapping_connection_string_to_namespace_name.cs
src/Tests/Topology/MetaModel/When_mapping_namespace_name_to_connection_string.cs
src/Transport/Topology/MetaModel/DefaultConnectionStringToNamespaceNameMapper.cs
src/Transport/Topology/MetaModel/DefaultNamespaceNameToConnectionStringMapper.cs

Related to this comment: https://github.com/Particular/docs.particular.net/pull/1455#discussion_r61830014
I'm not sure if `InvalidOperationException` is fine. 

Improved exception message

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/Addressing/AddressingLogic.cs
src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Topology/ITopology.cs
src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs

Fix addressing logic (against release)

---

src/Transport/Config/AzureServiceBusTransport.cs

Provide meaningful exception when topology is not configured

---

README.md

Updated readme.md for environment setup

---

src/Transport/Topology/TopologyOperator.cs

Remove unused cts

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config

A few [bug fixes](https://www.nuget.org/packages/WindowsAzure.ServiceBus/3.2.2) related to messaging  in the ASB library.

Update to ASB v3.2.2

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0-beta0003/Sagas/When_saga_id_changed.cs
src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs

Generate unique transport message id

---

src/Tests/Configuration/When_using_default_configuration.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/Config/DefaultConfigurationValues.cs

Set correct default for subscriptions DeliveryCount

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Addressing/Individualization/When_using_discriminator_individualization_strategy.cs
src/Tests/Configuration/When_configuring_individualization.cs
src/Transport/Addressing/Individualization/IIndividualizationStrategy.cs
src/Transport/Addressing/Individualization/Strategies/CoreIndividualization.cs
src/Transport/Addressing/Individualization/Strategies/DiscriminatorBasedIndividualization.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusDiscriminatorBasedIndividualizationSettingsExtensions.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusIndividualizationExtensionPoint.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusIndividualizationSettings.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/NServiceBus.AzureServiceBus.csproj

Allow to set discriminator generator for discriminator based individualization

---

src/Tests/Topology/When_configuring_publishers.cs
src/Transport/Topology/PublishersConfiguration.cs

Connects to #180 
The only concern I have related to add suggestions about how to fix issue inside the exception message, is that configuration API could change in the future and we'll have to remember to upgrade the exception message too. Without any help from compiler or tests
@Particular/azure-service-bus-maintainers ping

Improve exception message for missing publishers

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Routing/When_scaling_out_senders_that_uses_callbacks.cs
src/AcceptanceTests/TransportEncoding/When_receiving_a_message_with_unknown_transport_encoding.cs
src/AcceptanceTests/packages.config
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Connectivity/When_executing_task_with_retry.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/Connectivity/MessagingFactoryAdapter.cs
src/Transport/Connectivity/NamespaceManagerAdapter.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config

@Particular/azure-service-bus-maintainers please review/merge

Upgrade to ASB v3.2.3

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Configuration/When_configuring_custom_brokered_message_to_incoming_message_converter.cs
src/Tests/Configuration/When_configuring_custom_outgoing_message_to_brokered_message_converter.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/ExtensionMethods/AzureServiceBusTransportExtensions.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs

Connects to #278 
@Particular/azure-service-bus-maintainers please review!

Config API to provide custom brokered message converter

---

src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Transport/Seam/Dispatcher.cs
src/Transport/Seam/MessagePump.cs

Shows how transport transaction was meant to be used.
@Particular/azure-service-bus-maintainers

Shows the usage of transport transaction

---

src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs

Connect to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/309

Reply-To header is not set correctly when using namespace aliases

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/ExtensionMethods/AzureServiceBusTransportExtensions.cs
src/Transport/Config/TransactionModeSettingsExtensions.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Connectivity/MessagingFactoryCreator.cs
src/Transport/Connectivity/NamespaceManagerAdapter.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/issues/306

Default TranssportType (SBMP vs AMQP)

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config

NUnit, FakeItEasy, GitVersion, Fody update

---

src/Transport/Config/AzureServiceBusTransportInfrastructure.cs

Made ToTransportAddress explicit

---

src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs

Connect to #319 
@Particular/azure-host-maintainers please review

Logging exception data using exception object overload

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Sending/When_converting_outgoing_messages_to_brokered_messages.cs
src/Tests/Topology/MetaModel/When_mapping_connection_string_to_namespace_alias.cs
src/Transport/Connectivity/MessageReceiverLifeCycleManager.cs
src/Transport/Connectivity/MessageSenderLifeCycleManager.cs
src/Transport/Sending/DefaultBatchedOperationsToBrokeredMessagesConverter.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Sending/RoutingOptions.cs
src/Transport/Topology/MetaModel/DefaultConnectionStringToNamespaceAliasMapper.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs

Covers https://github.com/Particular/NServiceBus.AzureServiceBus/issues/322
Covers https://github.com/Particular/NServiceBus.AzureServiceBus/issues/325
Covers https://github.com/Particular/NServiceBus.AzureServiceBus/issues/323

Bugs discovered during implementing custom namespace partitioning

---

GitVersion.yml

Solves https://github.com/Particular/NServiceBus.AzureServiceBus/issues/321

changed yaml to yml and added rc release tag

---

src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Tests/Seam/When_purge_on_startup_is_enabled.cs
src/Tests/Seam/When_receiving_messages.cs
src/Transport/Config/AzureServiceBusTransport.cs
src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Seam/MessagePump.cs

Addressing the comments on https://github.com/Particular/NServiceBus.AzureServiceBus/pull/327 by @yvesgoeleven

Address Rc2 review comments

---

src/NServiceBus.AzureServiceBus.sln.DotSettings
src/Tests/Configuration/When_using_default_configuration.cs
src/Tests/Creation/When_creating_queues.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs

Connect to #308 
A few questions raised in the issue. @Particular/azure-service-bus-maintainers please answer those first.

Delivery count as immediate retries

---

packaging/nuget/nservicebus.azureservicebus.nuspec
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

ASB 3.4.0 upgrade + Core RC2 in nuspec fix

---

src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Sending/When_sending_a_large_batch.cs
src/AcceptanceTests/Sending/When_sending_more_than_100_messages_in_a_transaction.cs
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Sending/TransactionContainsTooManyMessages.cs

Transaction with batch > 100 msgs

---

src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs

Reverts Particular/NServiceBus.AzureServiceBus#357

Revert "Concurrency set to zero"

---

src/Transport/Connectivity/MessageReceiverLifeCycleManager.cs
src/Transport/Connectivity/MessageSenderLifeCycleManager.cs
src/Transport/Connectivity/MessagingFactoryLifeCycleManager.cs
src/Transport/Receiving/MessageReceiverNotifier.cs

- removed `lock` statements
- creation of message receivers in parallel

Speeding up startup

---

src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs

fixes #365 
fixes #364 (cherry picked from develop)

hotfix-7.0.1

---

src/Transport/Receiving/MessageReceiverNotifier.cs

Fixes #369 
[See details](https://github.com/Particular/NServiceBus.AzureServiceBus/issues/369#issue-182890682) on changes in the general description.

LockTokens is null or empty exception on endpoint shutdown #369

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Transport/Config/AzureServiceBusTransport.cs
src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Connectivity/MessageReceiverLifeCycleManager.cs
src/Transport/Connectivity/MessageSenderLifeCycleManager.cs
src/Transport/Connectivity/MessagingFactoryLifeCycleManager.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Topology/IStoppableTopology.cs
src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/TopologyOperator.cs

Includes the following:
- Fix for #337 (ObjectDisposedException)
- Fix for #369 (empty lockTokens collection)
- Startup speed up #360 
- Internal fix for #381 (NullReferenceException because of optimization in #360)

Hotfix 7.0.2

---

README.md

@Particular/azure-host-maintainers this will show what's the current version of the transport we have on nuget straight on the readme.md

nuget version shield

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Publishing/When_using_a_signle_bundle.cs
src/Tests/Topology/Sending/When_sending_through_ForwardingTopology.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs

Use first topic in events bundle

---

src/Transport/Receiving/MessageReceiverNotifier.cs

When we are shutting down we want to immediately unsubscribe from OnMessage API\`s `ExceptionReceived` event since we are closing the message receivers and we don't want to unnecessarily trigger the circuit breaker as well as risking to run into double shutdown over the critical error action.

Unsubscribe from exceptions

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
src/Transport/Creation/ICreateAzureServiceBusSubscriptions.cs

Removing physical subscription entity on unsubscribe.

Remove physical subscriptions on unsubscribe

---

src/Transport/Receiving/MessageReceiverNotifier.cs

Attempt to tackle the shutdown issues we see. I figured it cannot hurt to have dedicated message options per receiver. With that each receiver attaches the event handler to its options. When we stop we remove the event handler from all the options. This should avoid races with the handler unsubscription.
The implementation of message options uses the race to initialize pattern
```
public event EventHandler<ExceptionReceivedEventArgs> ExceptionReceived
{
add
{
EventHandler<ExceptionReceivedEventArgs> eventHandler = this.ExceptionReceived;
EventHandler<ExceptionReceivedEventArgs> comparand;
do
{
comparand = eventHandler;
eventHandler = Interlocked.CompareExchange<EventHandler<ExceptionReceivedEventArgs>>(ref this.ExceptionReceived, (EventHandler<ExceptionReceivedEventArgs>) …
```

Using dedicated OnMessageOptions per receiver

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Updated to the latest ASB client

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Upgrade ASB to 3.4.2

---

src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs

Verification test for [fix](c05a322ce8ff8fd0094ddde256aab80caf9f5512) made in #412 as per https://github.com/Particular/NServiceBus.AzureServiceBus/pull/412#issuecomment-260710778.
The change forces Router to send messages over active namespaces and only if that fails, to send over passive namespaces.

Verify that messages are routed to the active namespace first

---

src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Creation/When_creating_topics.cs
src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Tests/Seam/When_purge_on_startup_is_enabled.cs
src/Tests/Seam/When_receiving_messages.cs
src/Transport/Addressing/Partitioning/IPerformNamespacePartitioningFailOver.cs
src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Seam/MessagePump.cs

#@internal issues will be used for release notes generation, not the PR
Hotfix for the following issues
- #411 (Topic existence is not verified with an associated namespace) ✔️ 
- #406 (FailOverNamespacePartitioning won't fail over): PRs: #415✔️, ~~#417✔️~~
- ~~#413 (RepeatedFailuresOverTimeCircuitBreaker is armed after a single error)❓~~
PR was started with fix to #411.

[WIP] hotfix 7.0.3

---

src/Transport/Utils/BrokeredMessageExtensions.cs

Closes https://github.com/Particular/NServiceBus.AzureServiceBus/issues/401

Fix spelling of occured to occurred

---

src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Topology/TopologyOperator.cs

Hotfix 7.0.4

---

src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_queues.cs
src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_topics.cs
src/Tests/PreStartupChecks/When_all_pre_startup_checks_for_forwarding_topology_fail.cs
src/Tests/PreStartupChecks/When_execute_manage_rights_startup_check.cs
src/Transport/Config/DefaultConfigurationValues.cs
src/Transport/Config/WellKnownConfigurationKeys.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Topology/PreStartupChecks/ManageRightsCheck.cs

Closes #424
For more details see the issue for details

Removing check of WellKnownConfigurationKeys.Core.CreateTopology for entity creation

---

src/Tests/Addressing/NamespacePartitioning/When_using_failover_namespace_strategy.cs
src/Tests/Creation/When_creating_topics.cs
src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs
src/Tests/Topology/Sending/When_sending_through_EndpointOrientedTopology.cs
src/Tests/Topology/Sending/When_sending_through_ForwardingTopology.cs
src/Transport/Addressing/Partitioning/Strategies/FailOverNamespacePartitioning.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
src/Transport/Topology/TopologyOperator.cs

Brings in changes from 7.0.4 to 7.10
Thanks to pair brain melting with @tmasternak and @Scooletz

Hotfix 7.0.4 to 7.1.0

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

ASB 3.4.3 update

---

src/Tests/Topology/When_configuring_publishers.cs
src/Transport/Topology/PublishersConfiguration.cs

Small fix for the exception message on the publisher configuration

Exception message points to UseEndpointOrientedTopology instead of UseTopology<T>

---

src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Tests/Seam/When_purge_on_startup_is_enabled.cs
src/Tests/Seam/When_receiving_messages.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/TopologyOperator.cs

Small step towards https://github.com/Particular/NServiceBus.AzureServiceBus/issues/448
- TopologyOperator and MessageReceiveNotifier are no longer resolved from the container

TopologyOperator and MessageReceiverNotifier gets no longer resolved on the container

---

src/Transport/Receiving/MessageReceiverNotifier.cs

Similar to PR #470, which fixes issue #466, just against `develop` branch.

Bringing fix #466 to the develop branch

---

src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Routing/When_unsubscribing.cs
src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs

Issue #459 (Subscription not removed when unsubscribing with `EndpointOrientedTopology`) that was fixed and cherry picked into `develop`.

Fix for issue #459 cherry picked from hotfix #462

---

src/AcceptanceTests/App_Packages/NSB.AcceptanceTests.6.0.0/Routing/NativePublishSubscribe/When_multi_subscribing_to_a_polymorphic_event.cs
src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Routing/When_subscribing_to_a_derived_polymorphic_event_with_forwarding_topology.cs
src/AcceptanceTests/Routing/When_unsubscribing.cs
src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Creation/When_creating_subscription.cs
src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
src/Transport/Connectivity/MessagingFactoryCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Topology/MetaModel/SubscriptionInfo.cs
src/Transport/Topology/Topologies/EndpointOrientedTopologySectionManager.cs

Candidates for this hotfix:
- #462 
- #463

Hotfix 7.1.1

---

src/Tests/Receiving/When_comparing_performance_for_prefetch.cs
src/Tests/Receiving/When_incoming_message_processing_takes_longer_than_LockDuration.cs
src/Tests/Receiving/When_receiving_brokeredmessages_from_queues.cs
src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
src/Tests/Seam/When_dispatching_messages.cs
src/Tests/Seam/When_dispatching_messages_in_receive_context.cs
src/Tests/Seam/When_receiving_messages.cs
src/Tests/Sending/When_comparing_performance_between_built_in_batching_and_manual.cs
src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs
src/Tests/Sending/When_sending_brokeredmessages_to_queues.cs
src/Transport/Connectivity/IManageMessageReceiverLifeCycle.cs
src/Transport/Connectivity/IManageMessageSenderLifeCycle.cs
src/Transport/Connectivity/MessageReceiverLifeCycleManager.cs
src/Transport/Connectivity/MessageSenderLifeCycleManager.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Topology/Topologies/EndpointOrientedTopology.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/TopologyOperator.cs

Another set of dependencies removed from the container.

Lifecyclemanager

---

src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Utils/TaskEx.cs

Per @danielmarbach's suggestion: https://github.com/Particular/NServiceBus.AzureServiceBus/pull/491#discussion_r99347790

Cache Task.FromResult(true)

---

src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs

- Unified key generation for cache in both topic and queue.
- Added namespace host to logging information
- Cached `FromResult(true)`

Minor topic and queue creation changes

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Smoke tested.
@Particular/azure-maintainers please review/merge

ASB 3.4.6 update

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Connects to https://github.com/Particular/NServiceBus.AzureServiceBus/pull/514
Bumping ASB dependency to v4.0.0 on the `develop` branch.

ASB 4.0.0 dependency update

---

src/AcceptanceTests/Receiving/When_incoming_message_lock_token_is_lost_in_send_atomic_with_receive_mode.cs

Connects to #532
Compensating PR for PR #534
This PR is intended to 
- Fix the squash commit of PR #534 done to the `master`
- Refactors the test to ensure it's consistent with the back-ported version in PR #537 (`hotfix-7.1.6`)

Compensating PR for the original PR #534

---

.gitignore
src/AcceptanceTests/Issues/When_publisher_and_subscriber_bundles_are_misconfigured.cs
src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/Publishing/When_using_a_signle_bundle.cs
src/Tests/API/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Connectivity/When_managing_namespace_manager_lifecycle.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/PreStartupChecks/When_executing_NumberOfTopicsInBundleCheck.cs
src/Tests/Topology/MetaModel/When_namespace_bundle_configurations_is_used.cs
src/Tests/Topology/Operation/When_operating_EndpointOrientedTopology.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusForwardingTopologySettingsExtensions.cs
src/Transport/Connectivity/INamespaceManager.cs
src/Transport/Connectivity/NamespaceManagerAdapter.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Topology/ITopology.cs
src/Transport/Topology/MetaModel/NamespaceBundleConfigurations.cs
src/Transport/Topology/MetaModel/NamespaceBundleInfo.cs
src/Transport/Topology/NumberOfTopicsInBundleCheck.cs
src/Transport/Topology/Topologies/ForwardingTopology.cs
src/Transport/Topology/Topologies/ForwardingTopologySectionManager.cs
src/Transport/Utils/MessageReceiverExtensions.cs

Connects to #524 
Misconfigured bundles can cause message loss (#551)

Hotfix 7.2.4

---

src/Transport/Sending/BatchedOperationsToBrokeredMessagesConverter.cs

simpler filtering

---

src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/ExceptionReceivedAction.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Sending/DefaultOutgoingBatchRouter.cs
src/Transport/Utils/ExceptionExtensions.cs
src/Transport/packages.config

Fixes #558 and #568 bugs.
@Particular/azure-maintainers please review.

Hotfix 7.2.6

---

src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Utils/ExceptionExtensions.cs

Fixes issue #568 in `develop` (Treat `TimeoutException`s as transient errors)

porting hotfix-7.2.6

---

src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs
src/Transport/Receiving/MessageReceiverNotifier.cs

No longer use settings at runtime in components under Receiving. Shows a simple approach which can be followed. Basically, each class that is used during runtime with a field of type `ReadonlySettings `is probably abusing the settings
Info: Creation namespace does not abuse the settings

Components in Receiving no longer use settings at runtime

---

src/Tests/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Configuration/When_configuring_subscriptions.cs
src/Tests/Configuration/When_configuring_topics.cs
src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_subscription.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusSubscriptionSettings.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusTopicSettings.cs

Closes https://github.com/Particular/NServiceBus.AzureServiceBus/issues/612

Description customizer

---

src/AcceptanceTests/Requires.cs
src/AcceptanceTests/Routing/When_subscribing_outside_the_endpoint_oriented_topology.cs
src/AcceptanceTests/Routing/When_subscribing_to_a_derived_polymorphic_event_with_forwarding_topology.cs
src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs

With core beta 7 the Requires class is partial. We can now leverage that.

Using partial requires class

---

src/Transport/Config/AzureServiceBusTransportInfrastructure.cs

Closes #627 
When queue names are used with the default sanitization or a custom sanitization strategy and either `DistributionContext.ToTransportAddress` or `TransportInfrastructure.ToTransportAddress` is called the queue name returned from that method will not comply with the queue name conventions of the transport.

Using addressingLogic to translate transport addresses

---

src/Directory.Build.props
src/NServiceBus.AzureServiceBus.sln
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/VisiblesTo.cs
src/Transport/obsoletes.cs
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Cleanup and removal of unnecessary items.

CSPROJ cleanups

---

src/Tests/ApprovalFiles/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Configuration/When_configuring_queues.cs
src/Tests/Configuration/When_configuring_topics.cs
src/Tests/Creation/When_creating_queues.cs
src/Tests/Creation/When_creating_topics.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusQueueSettings.cs
src/Transport/Config/ExtensionPoints/AzureServiceBusTopicSettings.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusTopicCreator.cs
src/Transport/Topology/TopologyQueueSettings.cs
src/Transport/Topology/TopologyTopicSettings.cs
src/Transport/obsoletes.cs

EnableExpress setting for queues and topics obsoleted

---

src/Tests/Seam/When_dispatching_messages.cs
src/Tests/Sending/When_batching_TransportOperations.cs
src/Transport/Config/AzureServiceBusTransportInfrastructure.cs
src/Transport/Sending/Batcher.cs
src/Transport/Topology/Topologies/EndpointOrientedTransportInfrastructure.cs

For send-only endpoint use translated endpoint name

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Directory.Build.props
src/NServiceBus.AzureServiceBus.sln
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/Topology/TypesScanner/When_configuring_an_assembly_scanner.cs
src/Transport/NServiceBus.AzureServiceBus.csproj
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

This cleans up a few things related to moving to the new project system and Particular.Packaging.
It also adds SourceLink support.

Project cleanup

---

src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs

Related to #667
Fixes #667
Anyone using NServiceBus.Azure.Transports.WindowsAzureServiceBus transport version 7 or greater with forwarding topology and endpoints that subscribe to more than one event.
Events that expected to be received are not received and the endpoint has a log message similar to the following:
`Subscription 'subscriptionName' in namespace 'namespaceHost' already exists, another node probably beat us to it."`

A race condition can prevent subscriptions from being created when using forwarding topology

---

src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs

Forward port of https://github.com/Particular/NServiceBus.AzureServiceBus/pull/668

Forward port: Rework forwarding topology creation using exists bool method

---

src/Tests/Topology/When_counting_existing_topics_in_bundle.cs
src/Transport/Topology/NumberOfTopicsInBundleCheck.cs

Connects to #675 
Fixes #675 by counting topics that follow a pattern for `bundle_prefix-NUMBER`.

Count topics in bundle with numeric values only

---

src/Tests/Topology/MetaModel/When_parsing_string_to_connection_string.cs
src/Transport/Topology/MetaModel/ConnectionString.cs

Fixes https://github.com/Particular/NServiceBus.AzureServiceBus/issues/686

Hotfix 7.2.11

---

src/Transport/Utils/BrokeredMessageExtensions.cs
src/Transport/Utils/MessageReceiverExtensions.cs

Connected to #702 
Fixes #702
The wording of exception message is incorrect. Batch Size was replaced by Prefetch Count.

Fix exception message confusion

---

src/Transport/Receiving/MessageReceiverNotifier.cs

Fix spelling error

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Receiving/MultiProducerConcurrentCompletion.cs
src/Transport/Topology/MetaModel/ConnectionString.cs
src/Transport/Topology/MetaModel/EntityAddress.cs
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Pending NServiceBus.Newtonsoft.Json

Prepare RTM

---

src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs
src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs

Accept incoming messages with transport encoding "application/octet-stream"

---

src/Tests/Receiving/When_converting_brokered_messages_to_incoming_messages.cs
src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs

Incoming messages can have transport as "octet-stream" or "octect-stream"

---

src/Transport/Receiving/INotifyIncomingMessages.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Topology/TopologyOperator.cs

Fixing concurrent subscribe issue

---

src/Tests/Creation/When_creating_forwarding_subscription.cs
src/Tests/Creation/When_creating_subscription.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusQueueCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Bring hotfix 8.0.2 to `develop`

Hotfix 8.0.2

---

src/Tests/Sending/When_comparing_performance_between_built_in_batching_and_manual.cs
src/Tests/Sending/When_routing_outgoingmessages_to_endpoints.cs

Replaces #746 to get a proper merge commit

Hotfix 8.0.3

---

src/NServiceBus.AzureServiceBus.sln.DotSettings
src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs
src/Transport/Seam/Dispatcher.cs
src/Transport/Sending/BatchedOperationsToBrokeredMessagesConverter.cs
src/Transport/Topology/MetaModel/EntityAddress.cs
src/Transport/Topology/TopologyOperator.cs

Udpate ReSharper solution file settings

---

src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/TransportTests/When_modifying_incoming_headers.cs

Do not mutate incoming message headers

---

src/Transport/Config/DefaultConfigurationValues.cs

Align default BatchFlushInterval with Microsoft ASB client default

---

src/Transport/Receiving/TransactionScopeSuppressFeature.cs

Remove duplicate registration

---

src/Tests/Topology/MetaModel/When_SqlSubscriptionFilter_is_serializing_an_event.cs
src/Transport/Topology/MetaModel/SqlSubscriptionFilter.cs

Simplify subscription rule (SQL filter expression)

---

src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Take ForwardTo into account when checking subscription entity equality

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Check forwarding rule match taking into account the path structure

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Hotfix 9.0.2

---

src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Hotfix 8.0.5

---

src/Tests/Creation/When_creating_subscription.cs
src/Tests/Creation/When_creating_subscription_backward_compatible_with_v6.cs
src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs
src/Transport/Creation/AzureServiceBusSubscriptionCreator.cs

Hotfix 7.2.14

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Bump ASB client

---

src/Tests/Receiving/When_converting_incoming_brokered_message.cs
src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs

Hotfix 8.0.6

---

src/Tests/Receiving/When_converting_incoming_brokered_message.cs
src/Transport/Receiving/DefaultBrokeredMessagesToIncomingMessagesConverter.cs

Hotfix 7.2.15

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/NServiceBus.AzureServiceBus.csproj
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

This updates development tooling on the `support-9.0` branch.
Note: It is okay for this to be squashed.

Update development tooling

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

@Particular/azure-maintainers please merge when green

Bump ASB to 5.1.0 for tests

---

src/AcceptanceTests/Receiving/When_messages_contains_typed_properties.cs
src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs

Fix type conversion problem for incoming message properties

---

src/AcceptanceTests/Receiving/When_messages_contains_typed_properties.cs
src/Transport/Receiving/BrokeredMessagesToIncomingMessagesConverter.cs

Backport of #803 to `support-8.0`

Custom header information is converted into null

---

src/Tests/Receiving/When_receiving_incomingmessages_from_queues.cs
src/Tests/Seam/When_message_pump_is_failing_to_receive_messages.cs
src/Transport/Receiving/INotifyIncomingMessages.cs
src/Transport/Receiving/MessageReceiverNotifier.cs
src/Transport/Seam/MessagePump.cs
src/Transport/Topology/IOperateTopology.cs
src/Transport/Topology/TopologyOperator.cs
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

Hotfix 9.1.3

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/AcceptanceTests/packages.config
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Tests/packages.config
src/Transport/NServiceBus.AzureServiceBus.csproj
src/Transport/packages.config
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj
src/TransportTests/packages.config

Replaces #815 
See https://github.com/Particular/NServiceBus.AzureServiceBus/pull/815 for details

Bump up NUnit to fix failing tests

---

GitVersion.yml
src/Transport/NServiceBus.AzureServiceBus.csproj

Update Particular.Packaging in release-8.0

---

GitVersion.yml
src/Transport/NServiceBus.AzureServiceBus.csproj

Update Particular.Packaging in release-9.1

---

GitVersion.yml
src/Transport/NServiceBus.AzureServiceBus.csproj

Update Particular.Packaging in master

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

For your review @mauroservienti

Update test projects to NServiceBus 7.2.3 in release-9.1

---

src/AcceptanceTests/NServiceBus.AzureServiceBus.AcceptanceTests.csproj
src/Tests/ApprovalFiles/APIApprovals.ApproveAzureServiceBusTransport.approved.txt
src/Tests/Creation/When_creating_the_transport.cs
src/Tests/NServiceBus.AzureServiceBus.Tests.csproj
src/Transport/Config/AzureServiceBusTransport.cs
src/Transport/FodyWeavers.xml
src/TransportTests/NServiceBus.AzureServiceBus.TransportTests.csproj

ASB legacy is going to be deprecated. This PR adds a warning to the user code.

Deprecation notice
